name: super_hero_new
description: A Flutter package to generate random super-hero names to be used as placeholder text. Rather than plain old random-word pairs, you can instead fill in with a super-hero name.
version: 1.0.3
homepage: https://github.com/mynote/super_hero

environment:
  sdk: ">3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter